---
- hosts: frames
  remote_user: '{{ admin_user }}'
  become: yes

  tasks:
    - include: tasks/users.yml
    - include: tasks/bootloader.yml
    - include: tasks/ttys.yml
    - include: tasks/misc_packages.yml
    - include: tasks/firewall.yml
    - include: tasks/wireless.yml
      when: 'wl_interface in ansible_interfaces'
    - include: tasks/splash.yml
    - include: tasks/fim.yml
