---
- hosts: frames
  remote_user: '{{ admin_user }}'
  become: yes

  tasks:
    - include: users.yml
    - include: bootloader.yml
    - include: ttys.yml
    - include: misc_packages.yml
    - include: firewall.yml
    - include: wireless.yml
      when: 'wl_interface in ansible_interfaces'
    - include: splash.yml
