---
- hosts: frames
  remote_user: '{{ admin_user }}'
  become: yes

  tasks:
    - name: 'remove alarm user'
      user:
        name: alarm
        state: absent
        remove: yes
    - name: 'lock root user'
      user:
        name: root
        expires: 1
    - name: 'kernel cmdline'
      copy:
        src: files/cmdline.txt
        dest: /boot/cmdline.txt
    - include: 'ttys.yml'
    - include: 'firewall.yml'
    #- include: 'wireless.yml'
