---
- hosts: local
  become: true

  vars:
    boot_mountpoint: "{{ lookup('env', 'PWD') }}/mount/boot"
    root_mountpoint: "{{ lookup('env', 'PWD') }}/mount/root"

  vars_prompt:
    - name: 'sd_device'
      prompt: 'Enter device name (e.g. sdc) CAREFUL!'
      private: no

  tasks:
    - name: 'Partition device'
      shell: 'sfdisk /dev/{{ sd_device }} < sdcard.sfdisk'
    - name: 'Make boot fs'
      command: 'mkfs.vfat /dev/{{ sd_device }}1'
    - name: 'Make root fs'
      filesystem:
        fstype: ext4
        dev: '/dev/{{sd_device}}2'
    - name: 'Mount boot partition'
      command: 'mount /dev/{{ sd_device }}1 {{ boot_mountpoint }} warn=no'
    - name: 'Mount root partition'
      command: 'mount /dev/{{ sd_device }}2 {{ root_mountpoint }} warn=no'
    - name: 'Extract root fs'
      unarchive:
        src: 'http://os.archlinuxarm.org/os/{{ os_tarball }}'
        dest: '{{ root_mountpoint }}'
        remote_src: true
    - name: 'Move boot files'
      shell: 'mv {{ root_mountpoint }}/boot/* {{ boot_mountpoint }}'
    - name: 'Unmount boot partition'
      command: 'umount {{ boot_mountpoint }}'
    - name: 'Unmount root partition'
      command: 'umount {{ root_mountpoint }}'
