- name: 'fb width'
  shell: "cat /sys/class/graphics/fb0/virtual_size | cut -f 1 -d ','"
  register: fb_width
- name: 'fb height'
  shell: "cat /sys/class/graphics/fb0/virtual_size | cut -f 2 -d ','"
  register: fb_height
- name: 'fb depth'
  shell: "cat /sys/class/graphics/fb0/bits_per_pixel"
  register: fb_depth

- name: 'fim prerequisites'
  pacman:
    name: '{{ item }}'
  with_items:
    - base-devel
    - openbsd-netcat
    - libpng

- name: 'aur directory'
  file:
    path: '/home/{{ admin_user }}/aur'
    state: directory
    owner: '{{ admin_user }}'
- name: 'fim package files'
  copy:
    src: files/fim
    dest: '/home/{{ admin_user }}/aur'
    owner: '{{ admin_user }}'
- name: 'check fim installation'
  command: 'pacman -Q fim'
  register: fim_check_result
  ignore_errors: true
- name: 'build fim'
  shell: 'PKGEXT=".pkg.tar" makepkg -csi --noconfirm --needed --noprogressbar'
  args:
    chdir: '/home/{{ admin_user }}/aur/fim'
  become: false
  when: fim_check_result.rc!=0

- name: 'fimrc file'
  copy:
    src: files/fimrc
    dest: /etc/fimrc
- name: 'fim service file'
  template:
    src: templates/fim.service.j2
    dest: /etc/systemd/system/fim.service
- name: 'fim service'
  systemd:
    unit: fim.service
    enabled: yes
    state: started
    daemon_reload: yes
