- name: 'nginx'
  pacman:
    name: nginx-mainline
    state: present
- name: 'nginx base config'
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - 'restart nginx'
- name: 'servers-available'
  file:
    path: /etc/nginx/servers-available
    state: directory
- name: 'servers-enabled'
  file:
    path: /etc/nginx/servers-enabled
    state: directory
- name: 'nginx service'
  systemd:
    unit: nginx.service
    enabled: yes
    state: started
